import { useState } from 'react';
import axios from 'axios';
import ReactMarkdown from 'react-markdown';
import { ArrowUpRight, BookOpen, Check, ChevronDown, ChevronRight, Code2, Copy, Github, ScanSearch, ShieldCheck, Sparkles, TriangleAlert } from 'lucide-react';

const API = import.meta.env.VITE_API_URL || 'http://localhost:8080/api';
const steps = ['Cloning repository…', 'Scanning source code…', 'Extracting documentation…', 'Running deterministic drift detection…', 'Preparing Gemini suggestions…'];

export default function App() {
  const [url, setUrl] = useState(''); const [report, setReport] = useState(null); const [loading, setLoading] = useState(false); const [step, setStep] = useState(0); const [error, setError] = useState(''); const [expanded, setExpanded] = useState(-1); const [copied, setCopied] = useState(-1);
  async function analyze(event) { event.preventDefault(); setError(''); setReport(null); setLoading(true); setStep(0); const timer=setInterval(()=>setStep(v=>Math.min(v+1,steps.length-1)),5000); try { const response=await axios.post(`${API}/repo/analyze`,{repositoryUrl:url.trim()},{timeout:180000}); setReport(response.data); } catch(e) {setError(e.response?.data?.message || 'Could not analyze this repository. Check the URL and make sure the backend and MySQL are running.');} finally {clearInterval(timer);setLoading(false);} }
  async function analyzeFixture(name){setError('');setReport(null);setLoading(true);setStep(3);try{const response=await axios.post(`${API}/repo/analyze-fixture/${name}`,{}, {timeout:180000});setReport(response.data);}catch(e){setError(e.response?.data?.message||'Could not scan the local fixture. Start the backend from its folder.');}finally{setLoading(false);}}
  async function copy(text,index){try{await navigator.clipboard.writeText(text||'');setCopied(index);setTimeout(()=>setCopied(-1),1800);}catch{setError('Clipboard access was denied by the browser.');}}
  const breakdown=report?.severityBreakdown || {};
  return <main className="page">
    <nav className="nav"><a className="brand" href="#top"><span className="brand-icon"><ScanSearch size={20}/></span>docdrift</a><span className="nav-note">DETERMINISTIC ANALYSIS <i/> GEMINI ASSISTED</span><a className="github-link" href="https://github.com" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={15}/></a></nav>
    <section className="hero" id="top"><div className="eyebrow"><span className="pulse"/> DOCUMENTATION QUALITY, AUTOMATED</div><h1>Code moves fast.<br/><span>Docs should keep up.</span></h1><p className="intro">Find the gap between what your repository does and what its documentation says. Get a clear report and practical suggestions.</p>
      <form className="scan-form" onSubmit={analyze}><Github size={19}/><input type="url" required placeholder="https://github.com/owner/repository" value={url} onChange={e=>setUrl(e.target.value)} disabled={loading}/><button disabled={loading}>{loading?'Scanning…':'Scan repository'} {!loading&&<ArrowUpRight size={16}/>}</button></form>
      <div className="demo-links"><span>Try a local demo:</span><button onClick={()=>analyzeFixture('drift')} disabled={loading}>With drift</button><button onClick={()=>analyzeFixture('clean')} disabled={loading}>No drift</button></div>
      <div className="trust-row"><span><Code2/> Source parsing</span><b>·</b><span><ShieldCheck/> Rule-based detection</span><b>·</b><span><Sparkles/> Optional AI suggestions</span></div>
    </section>
    {loading&&<section className="loading card"><div className="spinner"/><div><strong>{steps[step]}</strong><p>Public repositories may take a minute to clone and inspect.</p></div><div className="loading-track"><span style={{width:`${(step+1)*20}%`}}/></div></section>}
    {error&&<div className="error"><TriangleAlert size={18}/><span>{error}</span></div>}
    {report&&<section className="results" id="results"><div className="section-head"><div><div className="eyebrow">SCAN REPORT</div><h2>Repository findings</h2></div><div className="repo-pill"><Github size={15}/>{report.repositoryUrl}</div></div>
      <div className="stats"><Stat label="Source items" value={report.codeItemsScanned} icon={<Code2/>}/><Stat label="Documented items" value={report.docItemsScanned} icon={<BookOpen/>}/><Stat label="Drift issues" value={report.totalIssues} icon={<TriangleAlert/>}/><div className="stat card severity-stat"><span className="stat-label">BY SEVERITY</span><div className="severity-counts"><span><i className="dot high"/>{breakdown.HIGH||0} high</span><span><i className="dot medium"/>{breakdown.MEDIUM||0} medium</span><span><i className="dot low"/>{breakdown.LOW||0} low</span></div></div></div>
      {!report.totalIssues?<div className="empty card"><div className="empty-icon"><Check/></div><h3>No documentation drift detected</h3><p>The extracted routes and documentation match for this scan.</p></div>:<div className="issue-list">{report.issues.map((issue,i)=><article className={`issue card ${expanded===i?'open':''}`} key={`${issue.type}-${issue.routePath}-${i}`}><button className="issue-summary" onClick={()=>setExpanded(expanded===i?-1:i)}><span className={`severity ${issue.severity.toLowerCase()}`}>{issue.severity}</span><span className="issue-type">{issue.type.replaceAll('_',' ')}</span><span className="issue-name">{issue.routeMethod?`${issue.routeMethod} ${issue.routePath}`:issue.itemName}</span><span className="issue-location">{issue.file||issue.docFile||'—'}{issue.line?`:${issue.line}`:issue.docLine?`:${issue.docLine}`:''}</span>{expanded===i?<ChevronDown/>:<ChevronRight/>}</button>{expanded===i&&<div className="issue-detail"><p className="description">{issue.description}</p><div className="detail-grid"><Detail title="SOURCE CODE" file={issue.file} line={issue.line} params={issue.parameters}/><Detail title="DOCUMENTATION" file={issue.docFile} line={issue.docLine} params={issue.documentedParameters}/></div><div className="suggestion-head"><span><Sparkles size={16}/> AI SUMMARY &amp; SUGGESTED FIX</span><button className="copy" onClick={()=>copy(issue.aiSuggestion||'AI summary is generated for the top two HIGH severity issues in each scan.',i)}>{copied===i?<Check size={14}/>:<Copy size={14}/>} {copied===i?'Copied':'Copy'}</button></div><div className="markdown"><ReactMarkdown>{issue.aiSuggestion||'Gemini summary is generated for the top two HIGH severity findings in each scan.'}</ReactMarkdown></div></div>}</article>)}</div>}</section>}
    <section className="how"><div className="eyebrow">A CLEAR, TRACEABLE WORKFLOW</div><h2>Find drift. Keep the fix yours.</h2><div className="workflow">{[['01','Clone','Read a public GitHub repository'],['02','Compare','Match source items against Markdown'],['03','Explain','See severity and optional AI suggestions']].map(([n,title,desc])=><div className="workflow-item" key={n}><span>{n}</span><h3>{title}</h3><p>{desc}</p></div>)}</div></section>
    <footer>DOCDrift <span>·</span> Source analysis is deterministic. AI only suggests wording for confirmed findings.</footer>
  </main>;
}
function Stat({label,value,icon}){return <div className="stat card"><div className="stat-icon">{icon}</div><span className="stat-label">{label}</span><strong>{value}</strong></div>}
function Detail({title,file,line,params=[]}){return <div className="detail-card"><span>{title}</span><strong>{file||'No matching item'}</strong>{line&&<small>Line {line}</small>}<p>Parameters: {params?.length?params.join(', '):'none detected'}</p></div>}
